version: "1"

services:
  db-adonis:
    image: mysql:8.0.30
    hostname: db-adonis
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_DATABASE: db_adonis
    restart: always
    ports:
      - "6032:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin_adonis:
    image: phpmyadmin:5.2.0
    links:
      - db-adonis
    environment:
      PMA_HOST: db-adonis
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8084:80

  app_adonis:
    build:
      context: ./app-Flash-Card-adonisjs
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    expose:
      - "3333"

# The database will be persistent among containers restarts.
volumes:
  dbdata:
