# Creation date : 11.02.2025
# Created by : Sam Sallaku
# Updated for AdonisJS v6 application
# 
version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app_adonis
        depends_on:
            - db
        ports:
            - "3333:3333"
        environment:
            TZ: UTC
            PORT: 3333
            HOST: 0.0.0.0
            LOG_LEVEL: info
            APP_KEY: QfhrAVVVKccxl311I1KFS2P8ZPsfNJLz
            NODE_ENV: development
            SESSION_DRIVER: cookie
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: root
            DB_PASSWORD: root
            DB_DATABASE: app_adonis
        volumes:
            - .:/app
            - /app/node_modules
        restart: always

    db:
        image: mysql:8.0.30
        container_name: db_adonis_new
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app_adonis
        restart: always
        ports:
            - "6034:3306"
        volumes:
            - dbdata:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: pma_adonis
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80

# The database will be persistent among containers restarts.
volumes:
    dbdata: