# Creation date : 11.02.2025
# Created by : Sam Sallaku
# Description : creates 2 containers. PHPMyAdmin, MySQL
# 
version: '3'

services:
    db:
        image: mysql:8.0.30
        container_name: db_adonis
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_user_pass
        restart: always
        ports:
            - "6034:3306"
        volumes:
            - dbdata:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: pma_adonis
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80


# The database will be persistent among containers restarts.
volumes:
    dbdata:


  
