version: '3.3'

services:
  db:
    image: mysql:8.0.30
    container_name: db_flashcards
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/var/lib/mysql
      - ./scripts:/scripts

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: db_flashcards_pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  adonis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_app
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    environment:
      TZ: UTC
      PORT: 3333
      HOST: 0.0.0.0
      LOG_LEVEL: info
      APP_KEY:
      NODE_ENV: development
      SESSION_DRIVER: cookie
    depends_on:
      - db

volumes:
  dbdata:
